captainVersion: 4

services:
  $$cap_appname:
    image: atendai/evolution-api:$$cap_evolution_api_version
    volumes:
      - $$cap_appname-evolution-instances:/evolution/instances
    environment:
      ## Configurações Gerais
      SERVER_URL: $$cap_server_url
      AUTHENTICATION_API_KEY: $$cap_authentication_api_key
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: 'true'
      DEL_INSTANCE: 'false'
      QRCODE_LIMIT: '1902'
      LANGUAGE: 'pt-BR'
      
      ## Configuração do Cliente
      CONFIG_SESSION_PHONE_VERSION: '2.3000.1015901307'
      CONFIG_SESSION_PHONE_CLIENT: 'OrionDesign'
      CONFIG_SESSION_PHONE_NAME: 'Chrome'
      
      ## Configuração do Banco de Dados
      DATABASE_ENABLED: 'true'
      DATABASE_PROVIDER: 'postgresql'
      DATABASE_URL: postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--$$cap_appname-postgres:5432/evolution
      DATABASE_CONNECTION_URI: postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--$$cap_appname-postgres:5432/evolution
      DATABASE_CONNECTION_CLIENT_NAME: 'evolution'
      DATABASE_SAVE_DATA_INSTANCE: 'true'
      DATABASE_SAVE_DATA_NEW_MESSAGE: 'true'
      DATABASE_SAVE_MESSAGE_UPDATE: 'true'
      DATABASE_SAVE_DATA_CONTACTS: 'true'
      DATABASE_SAVE_DATA_CHATS: 'true'
      DATABASE_SAVE_DATA_LABELS: 'true'
      DATABASE_SAVE_DATA_HISTORIC: 'true'
      DOTENV_CONFIG_PATH: '/dev/null'
      
      ## Integração com OpenAI
      OPENAI_ENABLED: 'true'
      
      ## Integração com Dify
      DIFY_ENABLED: 'true'
      
      ## Integração com Typebot
      TYPEBOT_ENABLED: 'true'
      TYPEBOT_API_VERSION: 'latest'
      
      ## Integração com Chatwoot
      CHATWOOT_ENABLED: 'true'
      CHATWOOT_MESSAGE_READ: 'true'
      CHATWOOT_MESSAGE_DELETE: 'true'
      CHATWOOT_IMPORT_DATABASE_CONNECTION_URI: postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--$$cap_appname-postgres:5432/chatwoot?sslmode=disable
      CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE: 'false'
      
      ## Configuração do Cache
      CACHE_REDIS_ENABLED: 'true'
      CACHE_REDIS_URI: redis://srv-captain--$$cap_appname-redis:6379/8
      CACHE_REDIS_PREFIX_KEY: 'evolution'
      CACHE_REDIS_SAVE_INSTANCES: 'false'
      CACHE_LOCAL_ENABLED: 'false'
      
      ## Configuração do S3
      S3_ENABLED: 'false'
      S3_ACCESS_KEY: ''
      S3_SECRET_KEY: ''
      S3_BUCKET: 'evolution'
      S3_PORT: '443'
      S3_ENDPOINT: ''
      S3_USE_SSL: 'true'

      ## Configuração do WhatsApp Business
      WA_BUSINESS_TOKEN_WEBHOOK: 'evolution'
      WA_BUSINESS_URL: 'https://graph.facebook.com'
      WA_BUSINESS_VERSION: 'v20.0'
      WA_BUSINESS_LANGUAGE: 'pt_BR'

      ## Telemetria
      TELEMETRY: 'false'
      TELEMETRY_URL: ''

      ## Configuração do WebSocket
      WEBSOCKET_ENABLED: 'false'
      WEBSOCKET_GLOBAL_EVENTS: 'false'

      ## Configuração do SQS
      SQS_ENABLED: 'false'
      SQS_ACCESS_KEY_ID: ''
      SQS_SECRET_ACCESS_KEY: ''
      SQS_ACCOUNT_ID: ''
      SQS_REGION: ''

      ## Configuração do RabbitMQ
      RABBITMQ_ENABLED: 'false'
      RABBITMQ_URI: 'amqp://USER:PASS@rabbitmq:5672/evolution'
      RABBITMQ_EXCHANGE_NAME: 'evolution'
      RABBITMQ_GLOBAL_ENABLED: 'false'
      RABBITMQ_EVENTS_APPLICATION_STARTUP: 'false'
      RABBITMQ_EVENTS_INSTANCE_CREATE: 'false'
      RABBITMQ_EVENTS_INSTANCE_DELETE: 'false'
      RABBITMQ_EVENTS_QRCODE_UPDATED: 'false'
      RABBITMQ_EVENTS_MESSAGES_SET: 'false'
      RABBITMQ_EVENTS_MESSAGES_UPSERT: 'true'
      RABBITMQ_EVENTS_MESSAGES_EDITED: 'false'
      RABBITMQ_EVENTS_MESSAGES_UPDATE: 'false'
      RABBITMQ_EVENTS_MESSAGES_DELETE: 'false'
      RABBITMQ_EVENTS_SEND_MESSAGE: 'false'
      RABBITMQ_EVENTS_CONTACTS_SET: 'false'
      RABBITMQ_EVENTS_CONTACTS_UPSERT: 'false'
      RABBITMQ_EVENTS_CONTACTS_UPDATE: 'false'
      RABBITMQ_EVENTS_PRESENCE_UPDATE: 'false'
      RABBITMQ_EVENTS_CHATS_SET: 'false'
      RABBITMQ_EVENTS_CHATS_UPSERT: 'false'
      RABBITMQ_EVENTS_CHATS_UPDATE: 'false'
      RABBITMQ_EVENTS_CHATS_DELETE: 'false'
      RABBITMQ_EVENTS_GROUPS_UPSERT: 'false'
      RABBITMQ_EVENTS_GROUP_UPDATE: 'false'
      RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE: 'false'
      RABBITMQ_EVENTS_CONNECTION_UPDATE: 'true'
      RABBITMQ_EVENTS_CALL: 'false'
      RABBITMQ_EVENTS_TYPEBOT_START: 'false'
      RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS: 'false'

      ## Configuração do Webhook
      WEBHOOK_GLOBAL_ENABLED: 'false'
      WEBHOOK_GLOBAL_URL: ''
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: 'false'
      WEBHOOK_EVENTS_APPLICATION_STARTUP: 'false'
      WEBHOOK_EVENTS_QRCODE_UPDATED: 'false'
      WEBHOOK_EVENTS_MESSAGES_SET: 'false'
      WEBHOOK_EVENTS_MESSAGES_UPSERT: 'false'
      WEBHOOK_EVENTS_MESSAGES_EDITED: 'false'
      WEBHOOK_EVENTS_MESSAGES_UPDATE: 'false'
      WEBHOOK_EVENTS_MESSAGES_DELETE: 'false'
      WEBHOOK_EVENTS_SEND_MESSAGE: 'false'
      WEBHOOK_EVENTS_CONTACTS_SET: 'false'
      WEBHOOK_EVENTS_CONTACTS_UPSERT: 'false'
      WEBHOOK_EVENTS_CONTACTS_UPDATE: 'false'
      WEBHOOK_EVENTS_PRESENCE_UPDATE: 'false'
      WEBHOOK_EVENTS_CHATS_SET: 'false'
      WEBHOOK_EVENTS_CHATS_UPSERT: 'false'
      WEBHOOK_EVENTS_CHATS_UPDATE: 'false'
      WEBHOOK_EVENTS_CHATS_DELETE: 'false'
      WEBHOOK_EVENTS_GROUPS_UPSERT: 'false'
      WEBHOOK_EVENTS_GROUPS_UPDATE: 'false'
      WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: 'false'
      WEBHOOK_EVENTS_CONNECTION_UPDATE: 'false'
      WEBHOOK_EVENTS_LABELS_EDIT: 'false'
      WEBHOOK_EVENTS_LABELS_ASSOCIATION: 'false'
      WEBHOOK_EVENTS_CALL: 'false'
      WEBHOOK_EVENTS_TYPEBOT_START: 'false'
      WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS: 'false'
      WEBHOOK_EVENTS_ERRORS: 'false'
      WEBHOOK_EVENTS_ERRORS_WEBHOOK: ''

      ## Configuração do Provider
      PROVIDER_ENABLED: 'false'
      PROVIDER_HOST: '127.0.0.1'
      PROVIDER_PORT: '5656'
      PROVIDER_PREFIX: 'evolution'

    caproverExtra:
      containerHttpPort: 8080
    depends_on:
      - $$cap_appname-postgres
      - $$cap_appname-redis

  $$cap_appname-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $$cap_postgres_user
      POSTGRES_PASSWORD: $$cap_postgres_password
      POSTGRES_DB: 'evolution'
    volumes:
      - $$cap_appname-postgres-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: 'true'

  $$cap_appname-redis:
    image: redis:alpine
    caproverExtra:
      notExposeAsWebApp: 'true'

volumes:
  $$cap_appname-evolution-instances: {}
  $$cap_appname-postgres-data: {}

caproverOneClickApp:
  variables:
    - id: $$cap_evolution_api_version
      label: Evolution API Version
      defaultValue: 'v2.1.0'
      description: Informe a versão da imagem atendai/evolution-api que deseja utilizar.
      validRegex: /^.+$/
    - id: $$cap_server_url
      label: Server URL
      defaultValue: 'https://wpp.crialabs.com.br'
      description: URL do servidor.
      validRegex: /^.+$/
    - id: $$cap_authentication_api_key
      label: Authentication API Key
      defaultValue: 'e46d7333230dccfc120e49ad707efd39'
      validRegex: /^.+$/
    - id: $$cap_postgres_user
      label: PostgreSQL User
      defaultValue: 'postgres'
      validRegex: /^[a-zA-Z0-9_]+$/
    - id: $$cap_postgres_password
      label: PostgreSQL Password
      defaultValue: 'your_postgres_password'
      validRegex: /^.+$/

  instructions:
    start: >-
      Este é um aplicativo de um clique do CapRover para o Evolution API com PostgreSQL e Redis.
      Preencha as variáveis necessárias e clique em "Deploy" para implantar o aplicativo.

    end: >
      A aplicação foi implantada com sucesso. Pode levar alguns minutos para que todos os serviços estejam em pleno funcionamento.

  displayName: Evolution API com PostgreSQL e Redis
  isOfficial: false
  description: Serviço API Evolution com PostgreSQL e Redis
  documentation: >
    Esta aplicação implanta o serviço Evolution API juntamente com um banco de dados PostgreSQL e um servidor Redis.
    Certifique-se de configurar corretamente as variáveis de ambiente e ajustar quaisquer parâmetros adicionais conforme necessário.
